### PR TITLE
Fix character spawn on pipe

### LINKED ISSUE #12: Location element not being notified of entering when Character is constructed

### PR DESCRIPTION
**Pull request by homok43**
The Character constrctor doesn't notify the element it places itself upon. 
This causes problems with the Pipe as it doesn't get occupied.

### CODE REVIEW

File: src/macaroni/model/element/Pipe.java [hunk 1]
```diff
@@ -108,8 +108,15 @@ public ActiveElement getEndpoint(int index) {
...
+        if (!occupied && endpoints.size() == 2) {
+            if (from == null) {
+                Random.setCharacterLocationBeforeEnteringPipe(this, endpoints.get(0));
+            } else if (neighbours.contains(from)) {
+                Random.setCharacterLocationBeforeEnteringPipe(this, from);
+            } else {
+                return false;
+            }
+
             if (effect.enter(character)) {
```
Comment (gabor7d2) [inline src/macaroni/model/element/Pipe.java:120]: I believe the effect should only be evaluated when 'from' is not null, because when spawning the players, we want the player to stay on the pipe that was specified as their starting location.

Comment (gabor7d2) [inline src/macaroni/model/element/Pipe.java:120]: I believe the effect should only be evaluated when 'from' is not null, because when spawning the players, we want the player to stay on the pipe that was specified as their starting location.

Comment (homok43) [reply src/macaroni/model/element/Pipe.java:120]: Resolved in #20
